chore(haskell): more docker scripts

diff --git a/docker-test b/docker-test
--- a/docker-test
+++ b/docker-test
@@ -32,11 +32,28 @@ then
   exit 2
 fi
 
+if [ "$(uname)" == "Linux" ]; then
+  STACK=stack
+else
+  STACK="$(dirname "$0")"/docker-stack
+fi
+
+STACK_BIN="$("$STACK" path --local-install-root | sed -E 's/\r//g')"/bin
+if [ ! -d "$STACK_BIN" ]; then
+  echo "Stack binary directory not found: $STACK_BIN" >&2
+  exit 1
+fi
+if [ ! -x "$STACK_BIN"/mybox ]; then
+  echo "'mybox' binary not found in: $STACK_BIN" >&2
+  exit 1
+fi
+
 CONTAINER=$(docker run \
   --rm \
   -d \
+  --platform linux/amd64 \
   -e GITHUB_TOKEN="$(gh auth token)" \
-  -v "$(stack path --local-install-root)"/bin:/usr/local/bin \
+  -v "$STACK_BIN":/usr/local/bin \
   -v "$OPT_TARGET":/opt/target \
   "$OPT_IMAGE" \
   /bin/sh -c 'until [ -f /stop ]; do sleep 1; done'
